## Basics of NumPy

In [1]:
import numpy as np

In [5]:
a=np.array([[[3,4,2,4],[3,45,3,3]],[[63,34,24,4],[5,5,4,3]]])
a.dtype

dtype('int32')

In [9]:
arr=np.ones((5,4,4),dtype='int32')
arr.ndim

3

### Random

In [12]:
b=np.random.random_sample((2,2))
b

array([[0.40458324, 0.34384239],
       [0.42917817, 0.96930745]])

In [29]:
c=np.random.randint(0,10,(4,4))
print(c)
d=np.random.random_sample(c.shape)

[[2 1 3 8]
 [6 5 5 1]
 [8 9 9 4]
 [5 8 2 8]]


###  shape like code

In [32]:
d=np.ones((5,5),dtype='int32')
d[1:4,1:4]=np.zeros((3,3),dtype='int32')
d[2,2]=9

### identity metrices

In [40]:
e=np.identity(5,dtype='int32')
f=np.identity(6,dtype='int32')

###  create an array

In [42]:
f=np.arange(5,9,2)
#create one dim array arange(start,end,step)

In [47]:
g=np.tile([[[6,5],[8,4]]],5)
#np.tile(value or array or list etc,shape or value)


In [54]:
h=np.repeat(f,5)
print(h)
h=np.repeat(f,(1,2))
print(h)
#np.repeat(value or array or list etc,how many time you want to repeat)
#it is same as the tile but it repeat value wise

[5 5 5 5 5 7 7 7 7 7]
[5 7 7]


In [56]:
a=np.linspace(0,14,10,dtype='int32')
a
#np.linspace(start,end,no of elements)

array([ 0,  1,  3,  4,  6,  7,  9, 10, 12, 14])

# Broadcasting of array

### If we want to broadcast two array any one them is having dim 1 or both having same dim else broadcasting is not possible ex: (6,3,2,8,1,2,1) and (6,1,2,1,9,1,8) can but (6,1,4) and (1,5,3) are not broadcasted

In [59]:
a=np.array([[2,3,4,4],[4,2,6,7]])
b=np.array([1])
c=a+b
d=a+1
e=a*b
print(c)
print(d)
print(e)

[[3 4 5 5]
 [5 3 7 8]]
[[3 4 5 5]
 [5 3 7 8]]
[[2 3 4 4]
 [4 2 6 7]]


# Indexing

In [61]:
a=np.array([[[3,5,5,6,7],[4,3,5,6,7]],[[3,5,5,6,7],[4,3,5,6,7]]])


In [65]:
#print all elements of 1st row
a[...,2]

array([[5, 5],
       [5, 5]])

In [67]:
#print 0th row,1st col and 2 to 4 values
a[0,1,2:5]

array([5, 6, 7])

In [69]:
#squeeze function which removes all dim having value 1
a=np.arange(25).reshape(5,5,1,1,1)
print(a.shape)
a=a.squeeze()
print(a.shape)

(5, 5, 1, 1, 1)
(5, 5)


In [70]:
#passes rows and columns as list
a[[0,2,3],[1,2,4]]


array([ 1, 12, 19])

In [71]:
#ix_ function
np.ix_([0,2],[0,2,3])

(array([[0],
        [2]]), array([[0, 2, 3]]))

In [168]:
#check if two array are same or they share a same memory
np.may_share_memory(a,b)

# universal functions

In [172]:
#max,min,sum etc
a=np.array([[[3,5,5,6,7],[4,3,5,6,7]],[[2,5,5,6,7],[4,3,5,6,7]]])
print(a.sum())
print(a.max())
print(a.min())

# einsum function

In [74]:
a=np.arange(9,dtype='int32').reshape(3,3)
b=np.linspace(11,19,9,dtype='int32').reshape(3,3)
print(a,b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [79]:
#Transpose of array
print(np.einsum('ij->ji',a))


[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [80]:
#To access diagonal element of array
print(np.einsum('ii->i',b))

[11 15 19]


In [82]:
#Element wise metrix multiplication
ele=np.einsum('ij,ij->ij',a,b)
print(ele)
#Traditional metrix multiplication
mul=np.einsum('ij,jk->ik',a,b)
print(mul)

[[  0  12  26]
 [ 42  60  80]
 [102 126 152]]
[[ 48  51  54]
 [174 186 198]
 [300 321 342]]
